<?php

declare(strict_types=1);

use Magento\Framework\View\TemplateEngine\Php;
use Infrangible\RetailStore\Block\Store;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Store $block */
?>

<?php echo $block->getChildHtml('retail_store_before'); ?>

<?php echo $block->getContent(); ?>

<?php echo $block->getChildHtml('retail_store_after'); ?>
